services:
  - type: web
    name: signsafe
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
    branch: main